name: x

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    uses: go-faster/x/.github/workflows/lint.yml@main
  commit:
    uses: go-faster/x/.github/workflows/commit.yml@main
  nancy:
    uses: go-faster/x/.github/workflows/nancy.yml@main
  codeql:
    uses: go-faster/x/.github/workflows/codeql.yml@main